[package]
name = "rev_buf_reader"
version = "0.1.0"
authors = ["André Vicente Milack <andrevicente.m@gmail.com>"]
edition = "2018"

[features]
default=[]
iovec=[]
read_initializer=[]

[dependencies]
memchr="2.2.0"
